### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jschaeke** [vdomos/domogik-plugin-mqtt#1]
Hi, 
Just tried latest develop on develop branch of domogik (to hook up the self-made arduino temp.sensors); but got this error below. CORRECTION: my mistake; I was still on the MASTER branch.. 
`
pi@raspberrypi:/opt/dmg/domogik-plugin-mqtt $ sudo dmg_package -i /opt/dmg/domogik-plugin-mqtt/
Install a package from a folder : /opt/dmg/domogik-plugin-mqtt
Error while reading the json file '/opt/dmg/domogik-plugin-mqtt/info.json' : Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/bin/package.py", line 505, in is_json_ok
    pkg_json = PackageJson(path = json_file)
  File "/opt/dmg/domogik/src/domogik/common/packagejson.py", line 164, in __init__
    raise PackageException(exp.value)
PackageException: 'Error validating the json: DataType in sensor sensor_pressure is not valid'
`

I opened info.json and see DT_Pression:
`"sensor_pressure": {
                        "name": "Pressure",
                        "incremental" : false,
                        "data_type": "DT_Pression",
`

**Comment by tikismoke** [comment]
Domos dt pressure as evolved in 2 different one if I remember depending if it is in hPa or mbar.

**Comment by tikismoke** [comment]
Jschaeke try changing dt_pression by one existing in Domogik datatype dt_pressure or something like this.

**Comment by jschaeke** [comment]
Yep, dt_pressure did the trick! Thanks!

**Comment by tikismoke** [comment]
You're welcome.
Eventually propose a PR for this.

**Comment by jschaeke** [comment]
Ooops... I was mistaken, I was on the master branch instead of develop. I noticed it as soon as I didn't saw the on/off command in the Admin page, something I want to use for my arduino relays. Really nice that MQTT protocol, and well supported...(eg esp8266) I am glad I learnt it via this plugin. Hopefully I get it all working.
