### ISSUE TITLE
Configuration not saved

### ISSUE THREAD

**Issue by jschaeke** [vdomos/domogik-plugin-mqtt#3]
With the latest develop version of domogik, this mqtt plugin configuration always defaults back and so it doesn't start. I need to restart it always manually. Although the configuration is well saved in the database (an ip instead of localhost) and the autolaunch option is set, the domogik configuration always displays localhost and no autostartup flag. However starting it, connects the mqtt client to the ip configured in the database, so it's definitely not connecting to localhost and using the values displayed in the domogik mqtt plugin page. When I update the configuration in mqtt plugin page and switch tab and come back, I see localhost again. 

This latest pull of domogik also gave me a non-working domoweb due to some mq errors (issue raised for that). I don't think it's related but things got broken... 

PS: probably it is a domogik issue but the velbus plugin configuration works as expected... so not general.

**Comment by vdomos** [comment]
I have the same error with last develop and with other plugin like weather.
On the 0.5-hotfix branch , all it's ok for me.
it's not relate to mqtt plugin.
Ticket for domogik insteed ?
