### ISSUE TITLE
Plugin crashes if no sensor added

### ISSUE THREAD

**Issue by jschaeke** [vdomos/domogik-plugin-mqtt#4]
On a fresh installation, the plugin won't start if just a dimmer command is added to domogik. This is because the Listen Topic list is probably empty. Adding a sensor and problem is solved.

**Comment by vdomos** [comment]
Yes, you 're right, I will add a test for that.

thank, for this feedback

**Comment by vdomos** [comment]
it's corrected

**Comment by jschaeke** [comment]
Thanks; this plugin should be submitted to the standard packages of Domogik. I've managed to integrate arduino, esp and qbus in Domogik with it.
